version: '3'

services:
  jekyll:
    build: .
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling --incremental
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/srv/jekyll/vendor/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle_cache: