apiVersion: v1
entries:
  backend:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-09T11:56:34.320673592Z"
    description: A Helm chart for Kubernetes
    digest: 89fffa72566dad5ebd656488307a89dfef857509d297c8cdb0fa9433cb1c6c39
    name: backend
    type: application
    urls:
    - https://github.com/magudb/unleash-flux-poc/releases/download/backend-1.0.0/backend-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-09T11:34:40.835092482Z"
    description: A Helm chart for Kubernetes
    digest: 4554979c4c1b61db531969e1ae438e5cec814c588b432c94160abcc17c3959b1
    name: backend
    type: application
    urls:
    - https://github.com/magudb/unleash-flux-poc/releases/download/backend-0.1.0/backend-0.1.0.tgz
    version: 0.1.0
  frontend:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-09T11:56:34.487126482Z"
    description: A Helm chart for Kubernetes
    digest: 9ca55c15eefad48dc15c1170dae849ca384f4a17048bdc7f76650966ee325468
    name: frontend
    type: application
    urls:
    - https://github.com/magudb/unleash-flux-poc/releases/download/frontend-1.0.0/frontend-1.0.0.tgz
    version: 1.0.0
generated: "2023-06-09T11:56:34.487143382Z"
